### PR TITLE
Make data have a generic type

### PR DESCRIPTION
**Pull request by pspeter3**
This might make it so the actions are a little clearer?

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Hey @pspeter3, thanks. Can you explain why and how?

Also, see https://github.com/hyperapp/hyperapp/pull/659#discussion_r176727888

**Comment by pspeter3** [comment]
In TypeScript, `any` is an extremely permissive type.

For example:

```ts
const increment: ActionType<{ count: number }, {}> = (amount: number) => (
    state,
    actions
) => state.count + amount;

// Should be a type error
increment("3");
```

With the idea I wanted to play with:

```ts
const increment: ActionType<number, { count: number }, {}> = amount => (
    state,
    actions
) => state.count + amount;

// Is a type error
increment("3");
// Is not a type error
increment(3);
```

The downside is you only get type safety on the first parameter.

**Comment by pspeter3** [comment]
I'll fix the tests if people think this is a good idea. This is a WIP.

**Comment by Swizz** [comment]
Im in favor of it. 
Can you provide an example of an actions without the need of data ?

**Comment by pspeter3** [comment]
@Swizz an empty action would have type `void`

```ts
const increment: ActionType<void, { count: number }, {}> = () => () => { return { count: 0 } };
```

**Comment by SkaterDad** [comment]
> @pspeter3 The downside is you only get type safety on the first parameter.

Actions can only take one argument anyway, so that shouldn't be an issue.

**Comment by pspeter3** [comment]
That's good to know

**Comment by jorgebucaran** [comment]
@pspeter3 Is this still a work in progress? What else do we need to resolve this issue?

**Comment by pspeter3** [comment]
I just resolved the test. I wish the `ActionsType` could carry through the generic prop but that's ok. Maybe something that could be handled with conditional types or more thought.

**Comment by jorgebucaran** [comment]
Long time no see! The current focus is on shipping V2, but I think we can merge here. I'll publish a new V1 patch at some point when I'm less busy. Thank you! 👋

**Pull request merged**
