### PR TITLE
add form attribute to readonly attributes list.

### PR DESCRIPTION
**Pull request by kiyonori-matsumoto**
form attribute for input tag is readonly, so following errors occurred and nothing is rendered.

```
Uncaught TypeError: Cannot assign to read only property 'form'
 of object '#<HTMLInputElement>'
```

I also created codepen samples that fails for rendering.
https://codepen.io/middleearth/pen/EeJoyK

I think this issue is same as #179 , but i wondered this fix is correct.

please tell me if something is wrong.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
👋 Hi! @kiyonori-matsumoto Thank you, for your PR. Would it be possible to have a more complete example? An example using at least one action and submitting the form would help.

**Comment by kiyonori-matsumoto** [comment]
Hi. @jorgebucaran thank you for your reviewing.

I created another sample that uses action to send data (to example.com).

https://codepen.io/middleearth/pen/zmYNRz

**Comment by jorgebucaran** [comment]
@kiyonori-matsumoto @frenzzy Could we discuss the merits of adding this feature? I'd like to know why anyone would ever need to write the \<input\> elements **outside** the form element.

**Comment by selfup** [comment]
Not everything needs to be wrapped in `<form>`

To be honest I haven't wrapped any inputs in a <form> for like 3 years now and haven't run into any issues 😂 

However I don't see why an input needs to be treated as a form? 🤔

**Comment by lukejacksonn** [comment]
@selfup forms also handle all the submission logic for you. So `onsubmit` will handle interactions like hitting enter in an input and `form.elements` will give you all the inputs in a given form which is handy when it comes to serialising inputted data. I'd highly recommend using `form` elements!

**Comment by selfup** [comment]
Oh interesting, I'll check that behavior out. Thanks for explaining 🎉

**Comment by kiyonori-matsumoto** [comment]
@lukejacksonn 
thank you for your comments.

@selfup @jorgebucaran 
It is now not rendered if we use `form` tag inside each table row from new chrome version(may be 69), and also firefox.

so if I use hyperapp, form and table rows, I must do like 2nd line of example shown below.

```html
<table><form><tr><td><input value="not shown" /></td></tr></form></table>
<table><form id="baz" /><tr><td><input value="shown" form="baz" /></td></tr></table>
```

I also updated my sample codepen to show the difference of the example.

https://codepen.io/middleearth/pen/zmYNRz

**Comment by jorgebucaran** [comment]
Does anyone know what React/Vue/Preact do in this case? 🤔

**Comment by frenzzy** [comment]
> ```html
> <table><form><tr><td><input value="not shown" /></td></tr></form></table>
> <table><form id="baz" /><tr><td><input value="shown" form="baz" /></td></tr></table>
> ```

@kiyonori-matsumoto this is [not valid html](https://validator.w3.org/), so of course it may not work properly:

image

If you will use valid html, maybe you don't need to use `form` attribute...

```html
<form><table><tr><td><input value="not shown" /></td></tr></table></form>
<table><tr><td><form><input value="not shown" /></form></td></tr></table>
```

**Comment by frenzzy** [comment]
> Does anyone know what React/Vue/Preact do in this case? 🤔

No runtime errors in React

React demo: https://codepen.io/frenzzy/pen/rqOQqB/left/?editors=0010
Hyperapp demo: https://codepen.io/frenzzy/pen/OByrba/left/?editors=0010

**Comment by kiyonori-matsumoto** [comment]
@frenzzy 
thank you for your comment.

I know that my html is invalid, but I want to apply form to each table row, like following.

```html
<table>
  <form><tr><td><input value="not shown" /></td><td><input /></tr></form>
  <form><tr><td><input value="not shown" /></td><td><input /></tr></form>
</table>
```

this html is also invalid, so I really wanted to use form attributes.

**Comment by frenzzy** [comment]
@kiyonori-matsumoto what about using non-table html markup?
```html
<div class="table">
  <form class="tr"><div class="td"><input /></div></form>
  <form class="tr"><div class="td"><input /></div></form>
</div>
```
```css
.table { display: table }
.tr { display: table-row }
.td { display: table-cell }
```
Demo https://codepen.io/frenzzy/pen/JmXmQm/left/?editors=1000

**Comment by frenzzy** [comment]
Personally I think this PR is good and I would accept it. Looks good to me.

**Comment by jorgebucaran** [comment]
Does this problem still happen?

**Comment by jorgebucaran** [comment]
@kiyonori-matsumoto Ping. 

> Does this problem still happen?

🤔

**Pull request closed without merging**
