### PR TITLE
Adds docs folder

### PR DESCRIPTION
**Pull request by sergey-shpak**
Fix for docs actions

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@sergey-shpak Where is this `dist` directory?

**Comment by sergey-shpak** [comment]
`dist` directory created by docs script `build` (which is triggered by `npm run build-site`):
https://github.com/jorgebucaran/hyperapp/blob/master/docs/package.json#L9

**Comment by jorgebucaran** [comment]
@sergey-shpak So there's actually never a `dist` directory in any branch, right?

**Comment by sergey-shpak** [comment]
yes, you are right, there is no any branch with `dist` directory (you can browse it only on local env, when building docs)

**Comment by jorgebucaran** [comment]
@sergey-shpak But it exists in GitHub servers when they build the page, and before they copy the files to `gh-pages`, correct?

**Comment by sergey-shpak** [comment]
@jorgebucaran yes, correct

**Pull request merged**
