### PR TITLE
Never mutate component props

### PR DESCRIPTION
**Pull request by frenzzy**
Alternative solution to https://github.com/jorgebucaran/hyperapp/pull/812

### CODE REVIEW

**Comment by SkaterDad** [comment]
This PR breaks `Lazy` again, since it is allowing the `children` prop to be attached, and it's a new array every time.

**Comment by frenzzy** [comment]
There are no tests in V2 branch 😢

**Comment by SkaterDad** [comment]
It should be fine again if you re-add the code I just PR'd.

**Comment by SkaterDad** [comment]
@frenzzy It's working again, thanks :+1:  

Tests really would be nice, but I can understand why they were deleted until the APIs are settled.

I'm a bit concerned about the overhead of copying props on every invocation of `h`.  Seems like an expensive thing to do.

If the component signature had stayed `(props, children)`, this wouldn't be an issue at all, right?

**Comment by frenzzy** [comment]
> If the component signature had stayed `(props, children)`, this wouldn't be an issue at all, right?

Exactly!

**Comment by jorgebucaran** [comment]
@SkaterDad @frenzzy What if we just go back to the (props, children) syntax? That would fix this no?

**Comment by jorgebucaran** [comment]
@SkaterDad @frenzzy What if we just go back to the (props, children) syntax? That would fix this no?

Sorry, I'm busy with other Hyperapp stuff and haven't gotten to this problem yet.

**Comment by SkaterDad** [comment]
> @SkaterDad @frenzzy What if we just go back to the (props, children) syntax? That would fix this no?
> 
> Sorry, I'm busy with other Hyperapp stuff and haven't gotten to this problem yet.

I think that'll fix it, since you won't have any need to mutate the `props` object being passed in.

I can't remember why the signature was changed to begin with.  Was it to make it easier to copy a JSX component from React to Hyperapp?

**Comment by jorgebucaran** [comment]
@SkaterDad Yes, but am I worrying too much? Performance-wise, how much this branch affects the benchmarks?

**Comment by frenzzy** [comment]
@jorgebucaran yes, `(props, children)` signature will solve the issue (HAv1 uses it and does not have this problem at all)

@SkaterDad reasons to change signature where here: https://github.com/jorgebucaran/hyperapp/issues/569

Back to `(props, children)` component signature: PR https://github.com/jorgebucaran/hyperapp/pull/814

**Comment by SkaterDad** [comment]
@frenzzy  Of the reasons listed, the one I think is most appealing is the potential to pass in context as another argument.  However, that could also be done V1-style in the future if needed, without a breaking change. 

```jsx
const comp = (props, children) => state => (<div>{children}</div>)
```

**Comment by jorgebucaran** [comment]
@SkaterDad What is this `context`? 🤔

**Comment by SkaterDad** [comment]
> @SkaterDad What is this `context`?

@frenzzy mentioned it in #569 as a speculative thing.

Could be anything you want, I suppose?  Theoretically it could be the global state, but we'd probably have to thread that all over the place to make it work.

For my own projects, I think the `(props, children)` signature for components is perfectly fine, and it avoids this mutated props issue.

**Comment by frenzzy** [comment]
Closing in favor of #814

**Pull request closed without merging**
