### PR TITLE
readme: add community packages/projects

### PR DESCRIPTION
**Pull request by atomiks**
I think there are some Hyperapp-related things currently missing from the docs. The README is seen as the one-stop source for everything Hyperapp (to me), so it makes sense that it should include these for visibility reasons.

### Starter Kit section

Why? Although beginners might use the "browser-only" method for toying around, they will want to also get started with a production app as well. Setting up Webpack can be difficult and they might not realise these exist. Linking to these starter kits lets them know there are ways get started with a build setup quickly.

### Packages section

Why? Solutions to common problems (routing, transitions, SSR) should be visible in the docs so readers know they exist without needing to externally search for them.

### CODE REVIEW

**Comment by selfup** [comment]
I can dig it 🙏

**Comment by jorgebucaran** [comment]
@atomiks Would it be feasible/convenient/a good idea to merge these two sections? And can we move them to the bottom?

**Comment by okwolf** [comment]
Would it be better to just add a single link to [awesome-hyperapp](https://github.com/hyperapp/awesome-hyperapp) and only keep that one up-to-date?

**Comment by jorgebucaran** [comment]
Looks good. V2 docs will have some of this stuff and then some other. Thanks!

**Pull request merged**
