### PR TITLE
Adds github actions workfows, builds and deploys docs into gh-pages branch

### PR DESCRIPTION
**Pull request by sergey-shpak**
This PR:
- adds [github actions workflows](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions)
- builds and deploys docs into gh-pages branch (to properly build and deploy #900 )

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thank you, @sergey-shpak! Could you explain what's going on here and what's going to happen if I merge this? Thanks!

**Comment by sergey-shpak** [comment]
sure, [Github Actions](https://github.com/features/actions):
> GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. Make code reviews, branch management, and issue triaging work the way you want.

Previously, to build/test or deploy your app/lib you had to run all scripts on your personal environment (local or external, like Jenkins for example), now you can use github and it's actions to create specific environment and run all the scripts. Github actions are free for public repos.

Github actions can be used for many hyperapp purposes, for example:
- automate npm publishing (on each release)
- automate docs bundling (on each push to master)
------------
This PR creates simple github action to automate docs bundling and pushing them to gh-pages branch

You can take closer look at [github actions syntax](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions), but let's walk through the `docs` action itself:
```yml
# .github/workflows/docs.yml

# name of the action
name: Build GH Docs

# Action runs:
# on any push to master branch
on:
  push:
    branches:
      - master

# list of actions jobs
jobs:
  # build and deploy job 
  build-and-deploy:
    # runs on latest ubuntu env
    runs-on: ubuntu-latest

    # list of job steps
    steps:

    # checkout repo (master)
    - name: Checkout
      # it uses public action to checkout (master)
      uses: actions/checkout@v1

    # build docs
    - name: Build
      # runs docs build script
      run: |
        npm run build-site

    # deploy docs to gh-pages branch
    - name: Deploy
      # it uses public action to push files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        # GITHUB_TOKEN is autogenerated *
        # it's required to allow public action to push to repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # gh-pages branch is default branch for github pages
        BRANCH: gh-pages
        # push to 'docs' dir
        FOLDER: docs
        # clean gh-pages/docs before push
        CLEAN: true
```
* [GITHUB_TOKEN](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token)

Main purpose of this PR is to automate docs build, and it has to be merged after #900 is merged

**Comment by jorgebucaran** [comment]
@sergey-shpak Sounds awesome. So, the gh-pages branch will only have the built files?

**Comment by jorgebucaran** [comment]
@sergey-shpak The site is now broken. Should I revert this?

**Comment by sergey-shpak** [comment]
@jorgebucaran `site` branch has been created and all the docs sources deployed: https://github.com/jorgebucaran/hyperapp/tree/site
so everything should work, can you check the github pages configuration?

**Comment by sergey-shpak** [comment]
@jorgebucaran docs are missing CNAME file. It is bundled with docs but not copied into `site` branch (and the reason for that is that [CNAME file is excluded from deployment process](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/git.ts#L148))

**Pull request merged**
