### PR TITLE
Effect dispatch

### PR DESCRIPTION
**Pull request by sergey-shpak**
PR allows to compose actions which return effects
```javascript

// effectA, effectB 

const actionA = state =>
  [state, [effectA]]

const actionB = state =>
  [actionA(state), [effectB]]

```

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@sergey-shpak I see what you mean. This is interesting, but I think it's too premature to add now since I don't have a use case for it. Maybe in the future.

**Comment by sergey-shpak** [comment]
@jorgebucaran it could be cherry on the hyperapp#2 cake :cake: :cake: :cake:

**Comment by sergey-shpak** [comment]
This PR is also quite good fit for simple as possible immutable enhancer (without trying to get state from effect tuple `setState(action[0])`)
```
const freeze = obj => {
  obj && Object.getOwnPropertyNames(obj).forEach(name =>
    typeof obj[name] == 'object' && freeze(obj[name]))
  return Object.freeze(obj)
}

const immutable = dispatch => 
  (action, props, obj) => dispatch(
    typeof action == 'object' && !Array.isArray(action)
    ? freeze(action)
    : action,
    props,
    obj
  )
// and then
app({...}, immutable)
```

**Comment by jorgebucaran** [comment]
I still think this is too hacky.

**Comment by sergey-shpak** [comment]
@jorgebucaran it is the same as `dispatch(action(state, props), obj || props)` or `dispatch(action[0], typeof (action = action[1]) === "function" ? action(props) : action, props)`, isn't it?

**Comment by jorgebucaran** [comment]
Is it? That's kind of hard to read hehe.

**Comment by jorgebucaran** [comment]
@sergey-shpak Not this time! But maybe in the future if there is a need for something like it.

**Pull request closed without merging**
