### PR TITLE
Enable support for DOM level 3+ case sensitive event types

### PR DESCRIPTION
**Pull request by websemantics**
Enable support for DOM level 3+ case sensitive event types #892

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@frenzzy @sergey-shpak @Swizz Are we happy to merge here?

**Comment by sergey-shpak** [comment]
@websemantics @jorgebucaran 
is it backward compatible? I mean If users have already used 'onClick' with hyperapp#2 apps/pens, this change will affect them.
* or this should be released as minor/major, not patch

**Comment by sergey-shpak** [comment]
@jorgebucaran ok, then I'm ok)

**Comment by Jesspu** [comment]
Is this getting merged in?

**Comment by okwolf** [comment]
I don't think we should be making breaking changes at this point.

**Comment by zaceno** [comment]
I'm curious: what are some examples of events we can't handle unless we merge this?

**Comment by jorgebucaran** [comment]
Forgot to merge this. We could since Hyperapp is still not "officially" released (poor excuse).

**Comment by jimfranke** [comment]
I think we should go with the following, which still allows for `onClick` instead of `onclick`, but also supports case-sensitive custom events.

```javascript
const keyLower = key.toLowerCase();
    if (
      !((node.actions || (node.actions = {}))[
	(keyLower in node ? keyLower : key).slice(2)
      ] = newValue)
    ) {
```

What do you think, @jorgebucaran?

**Comment by jorgebucaran** [comment]
@jimfranke I'm going to merge here first, then we can consider bringing that in the future! Thank you, @websemantics.

**Comment by jorgebucaran** [comment]
@jimfranke Revisiting this. Could you clarify:

> but also supports case-sensitive custom events.

**Comment by jorgebucaran** [comment]
@websemantics @jimfranke I'd also like to know the answer to:

> @zaceno I'm curious: what are some examples of events we can't handle unless we merge this?

**Comment by websemantics** [comment]
Thanks @jorgebucaran, take the [Alert](https://ionicframework.com/docs/api/alert) element in [Ionic Framework](https://ionicframework.com) for example `ionAlertDidDismiss` is case-sensitive. Also check the type attribute in [Changes to DOM Level 2 Events interfaces](https://www.w3.org/TR/uievents/#changes-DOMLevel2to3Changes).

**Comment by Jesspu** [comment]
I ran into the same issue. I tried using ionic web components with hyper
app for a hybrid mobile app and could not get some of ionics events to
work. If this was resolved i would love to be able to use ionics (or other)
web components with case sensitive events with hyper app.

**Comment by jorgebucaran** [comment]
@websemantics Would [this solution](https://github.com/jorgebucaran/hyperapp/pull/892#issuecomment-598660865) allow both to work? 

@Jesspu We merged this a while ago, so it's how Hyperapp works right now, but I was revisiting some old issues and wanted to fully understand why we dropped support for onClick, etc.

**Comment by websemantics** [comment]
@jorgebucaran Yes, just tested it and it works nicely. Also, with a bit of tweaking we can get `onIonAlertDidDismiss` work too.

**Pull request merged**
