### PR TITLE
Allow lazy component to return null in TypeScript

### PR DESCRIPTION
**Pull request by hasparus**
Types #636.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thanks, @hasparus! 👋

**Comment by infinnie** [comment]
They should also be able to return arrays.

**Comment by jorgebucaran** [comment]
@infinnie Why?

**Comment by infinnie** [comment]
@jorgebucaran Normal components can return arrays. Lazy components should behave similarly.

**Comment by jorgebucaran** [comment]
@infinnie But what does that have to with this PR?

**Pull request merged**
