### PR TITLE
Remove lib (@hyperapp/*) scoped packages

### PR DESCRIPTION
**Pull request by jorgebucaran**
Now it's up to you to create your own effects and subscriptions.

The intention is to give you more freedom in exchange for some initial user-friendliness and make Hyperapp easier to maintain in the long term.

We still encourage you to create reusable effects and subscriptions, rather than ad-hoc solutions to solve specific problems.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Hi @jorgebucaran.  Thanks a lot for your work.

Given that there are lots of tutorials on the web that point to `lib/` (including https://medium.com/hyperapp/a-walk-through-hyperapp-2-b1f642fca172 , this bug tracker), and preciously few examples of how to wire events yourself, it would be nice to resurrect `lib/`, at least as examples.  The current situation is pretty confusing.

One way could be to have `lib/` contain just a README and no files; the README would point to an `examples/` directory containing the old `lib/` code.

**Comment by jorgebucaran** [comment]
@cpitclaudel You are right. What are currently considering is bringing them back, but slowly and experimentally. While Hyperapp itself is essentially done, getting right each lib/module API is going to take a while.

See the notes under _experimental_ in https://github.com/jorgebucaran/hyperapp/pulls.

**Comment by cpitclaudel** [comment]
:+1: Thanks a lot for your hard work.

**Comment by jorgebucaran** [comment]
Thank you so much! 💯

**Comment by jarednorman** [comment]
Why were the packages unpublished from npm as well? We had a project using the `events` package and while it was trivial to resolve ourselves, it was super annoying to have all our builds broken by the npm package getting unpublished.

**Comment by jorgebucaran** [comment]
You are right, I should've deprecated it instead. Glad to know you resolved the issue, though.

**Comment by jorgebucaran** [comment]
You are right, I should've deprecated it instead. But I'm glad to know you resolved the issue!

**Comment by jorgebucaran** [comment]
You are right, I should've deprecated it instead. But I'm glad to hear the issue has been resolved!

**Pull request merged**
