### PR TITLE
V2 css enhance

### PR DESCRIPTION
**Pull request by cbbfcd**
just like this:

```js
// the props
{
  style: {
     color: 'orange !important'
  }
}
```

according to this 👉[setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)

⚠️：value must not contain "!important" -- that should be set using the priority paramete

and i have a  test: 
```
// it's no use
someNode.style.color = 'orange !important'
```

So I think there should be a test about importance here.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Using important is usually a last resort.. is using important on inline styles ever advised? Or are you just going for complete/closeness to the spec?

**Comment by mrozbarry** [comment]
Is this necessary? Inline styles always take precedence unless a css style was already marked as `!important` elsewhere. Furthermore, like @lukejacksonn said, marking `important` styles is always a last resort, so maybe we shouldn't encourage it.

@cbbfcd  Are you running into an issue where you can't use css and must flag the inline style as important?

**Comment by frenzzy** [comment]
Have you tried to use `cssText`? Why don't you like it?
```jsx
<div style={{ cssText: 'color:orange !important' }} />
```
Your approach will not work with styles in lowerCamelCase like this one:
```jsx
<div style={{ fontSize: '32px !important' }} />
```

**Comment by cbbfcd** [comment]
@lukejacksonn

Sorry, I did some research. My idea is indeed wrong. Thank you for your correction.

**Comment by cbbfcd** [comment]
> Have you tried to use `cssText`? Why don't you like it?
> 
> ```js-jsx
> <div style={{ cssText: 'color:orange !important' }} />
> ```
> 
> Your approach will not work with styles in lowerCamelCase like this one:
> 
> ```js-jsx
> <div style={{ fontSize: '32px !important' }} />
> ```

yep,

My idea is indeed wrong. thank u very much.

**Comment by cbbfcd** [comment]
> Is this necessary? Inline styles always take precedence unless a css style was already marked as `!important` elsewhere. Furthermore, like @lukejacksonn said, marking `important` styles is always a last resort, so maybe we shouldn't encourage it.
> 
> @cbbfcd Are you running into an issue where you can't use css and must flag the inline style as important?
> 
> Another thing to consider is that [react has not put any stance on using !important](https://github.com/facebook/react/issues/1881) either.

My idea is indeed wrong. thank u very much

**Comment by jorgebucaran** [comment]
@cbbfcd Could you merge or remove your duplicate comments? Thanks.

**Pull request closed without merging**
